version: '1.0' 
services:
  mongo_prod:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo_prod

  redis_prod:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis_prod


  backend_prod:                    
    image: todo-backend-prod
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile    
    container_name: todo-backend-prod
    environment: 
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo_prod
      - redis_prod
      - app_prod
      
  app_prod:
    image: todo-front-prod
    build:
      context: ./todo-frontend/ 
      dockerfile: Dockerfile 
    container_name: todo-front-prod

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - backend_prod
      - app_prod

